platform :ios, '7.0'
inhibit_all_warnings!

target :Rayzit do
    pod 'RestKit',            '0.23.2'
    pod 'MagicalRecord',      '2.2'
    # pod 'MBProgressHUD',      '0.9'
    pod 'Reachability',       '3.1.1'
    pod 'PonyDebugger',       '0.4.0',    :configurations => ['Debug', 'Debug localhost']
    pod 'CocoaLumberjack',    '1.9.1'
    pod 'SZTextView',         '1.1.10'
    pod 'DAProgressOverlayView','1.0.2'
    pod 'MWPhotoBrowser',       '1.4.1'
    pod 'MZFayeClient',         '1.0.0'
    pod 'SwipeView',          '1.3.2'
  # pod 'CocoaLumberjack',    '1.9.1'
end

target :RayzitTests, :exclusive => true do
    pod 'Specta',               '0.2.1'
    pod 'Expecta',              '0.3.1'
    pod 'OCMock',               '3.1.1'
    pod 'OCHamcrest',           '4.0.1'
    pod 'KIF',                  '3.0.8'
end